
artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/Vikash9570/Data/raw/main/bike_sharing%20(1).csv
  local_data_files: artifacts/data_ingestion/data.csv
  train_data_path: artifacts/data_ingestion/train_data.csv
  test_data_path: artifacts/data_ingestion/test_data.csv



data_transformation:
  root_dir: artifacts/data_transformation
  local_data_path: artifacts/data_ingestion/data.csv
  train_data_path: artifacts/data_ingestion/train_data.csv
  test_data_path: artifacts/data_ingestion/test_data.csv
  pickel_file_path: artifacts/data_transformation/preprocessor.pkl
  train_arr_path: artifacts/data_transformation/train_arr.txt
  test_arr_path: artifacts/data_transformation/test_arr.txt



model_trainer:
  root_dir: artifacts/model_trainer
  train_arr_path: artifacts/data_transformation/train_arr.txt
  test_arr_path: artifacts/data_transformation/test_arr.txt
  pickel_file_path: artifacts/model_trainer/model.pkl

predicting:
  preprocessor_pickel_file_path: artifacts/data_transformation/preprocessor.pkl
  model_pickel_file_path: artifacts/model_trainer/model.pkl
